"""
processing/cleaning/ftfy_cleaner.py

What problem does this solve?
- PDFs generated by older Windows tools, non-UTF-8 web pages, or documents
  exported through bad encoding pipelines contain mojibake — garbled text
  where Unicode characters were mis-encoded then decoded with the wrong codec.
  Example: "It\xe2\x80\x99s a caf\xc3\xa9" appears as "Itâ€™s a cafÃ©".
  Our UnicodeNormalizer handles typographic variants (curly quotes → straight)
  but does NOT fix mojibake — that requires ftfy.

Why ftfy specifically?
- ftfy (fixes text for you) implements a heuristic pipeline that detects and
  repairs encoding errors: UTF-8 decoded as Latin-1, double-encoded UTF-8,
  HTML entities left unescaped (&amp; → &), and more.
- It is the standard library for this problem — used by spaCy, AllenNLP,
  and most production NLP pipelines that ingest real-world documents.

Why run ftfy BEFORE WhitespaceCleaner (first in the pipeline)?
- ftfy may expand escaped sequences (e.g. "&amp;amp;" → "&amp;" → "&").
  Running it first ensures downstream cleaners see clean text.
- Whitespace cleaning on mojibake text can corrupt it further by stripping
  characters that look like control chars but are part of mis-encoded sequences.

Why a separate class instead of adding ftfy.fix_text() to WhitespaceCleaner?
- Single responsibility: each cleaner does one thing.
- FtfyCleaner can be disabled/removed without touching WhitespaceCleaner.
- Tests for encoding repair don't need to test whitespace logic.
"""

from agent.processing.cleaning.base import BaseTextCleaner

try:
    import ftfy as _ftfy
    _FTFY_AVAILABLE = True
except ImportError:
    _FTFY_AVAILABLE = False


class FtfyCleaner(BaseTextCleaner):
    """
    What problem does this solve?
    - Repairs mojibake and encoding corruption in document text before any
      other cleaning stage touches it.

    Why does this class exist?
    - First stage in PreprocessingPipeline. All subsequent cleaners assume
      clean Unicode — ftfy is what makes that assumption valid.

    Why graceful fallback when ftfy is missing?
    - ftfy is a soft dependency. If it is not installed, the cleaner returns
      the text unchanged with a warning rather than crashing the pipeline.
      The rest of the pipeline still runs; only encoding repair is skipped.
    """

    @property
    def name(self) -> str:
        return "FtfyCleaner"

    def clean(self, text: str, source_type: str = "unknown") -> str:
        """
        What problem does this solve?
        - Converts garbled encoded text into correct Unicode.

        Why is source_type accepted but unused?
        - Interface compliance with BaseTextCleaner.
          Encoding corruption is format-agnostic — same fix applies to PDF,
          DOCX, email, HTML.

        What ftfy.fix_text() does internally:
        1. Detects encoding errors (UTF-8 decoded as Latin-1, etc.)
        2. Re-encodes and re-decodes with the correct codec
        3. Normalises to NFC Unicode form
        4. Unescapes HTML entities (&amp; → &, &nbsp; → space)
        5. Fixes ligature splits (ﬁ → fi)

        Args:
        - text:        Raw text from the document loader.
        - source_type: Document format (unused — kept for interface compliance).

        Returns text with encoding errors repaired. Returns input unchanged
        if ftfy is not installed.
        """
        if not text:
            return text

        if not _FTFY_AVAILABLE:
            return text

        return _ftfy.fix_text(text)
